### ISSUE TITLE
add ability to pin tasks and combine tasks and launchers

### ISSUE THREAD

**Issue by librewish** [dangvd/ksmoothdock#103]
it doesn't feel like a dock with 
seperate launcher and task manager

**Comment by YemelesCorp** [comment]
I agree. This dock is exactly what I have been looking for and I love it so far. Latte dock just didn't seem smooth enough for me but this is exactly how a dock should feel. Just that one problem, the seperated launchers and tasks. Love it and I'm going to be using it without launchers 100%.

**Comment by dangvd** [comment]
Thanks for your comments.

Just out of curiosity, why don't you use Plank, Docky or Cairo Dock? Is it because they are Gtk/Gnome-based rather than Qt/KDE-based? Or are they not smooth enough?

Another question is, are you looking for a clone of MacOSX Dock (e.g. with dots under the task/launcher), or are you ok with, for example, Windows 10 look?

I originally designed KSmoothDock with separate launchers and tasks in mind, but I could try to take another look if/when I have some free time.

**Comment by YemelesCorp** [comment]
I'm running the latest Manjaro KDE on both my desktop an laptop. I tried Plank and Latte and they seemed slow. The animations felt unsmooth and unresponsive but your dock seems to work perfectly. I'm personally after that MacOS look that you currently have but really I just love the animations and would be happy with just about any look. I respect that you might not have free time to do it and I'm very grateful for your work so far.

**Comment by dangvd** [comment]
I see, thanks!

Sure, this will be the next major feature that I will work on.

**Comment by dangvd** [comment]
Released in v6.0
