### ISSUE TITLE
Freeze on constant switch with 4 virtual desktops with different wallpapers

### ISSUE THREAD

**Issue by andrecbarros** [dangvd/ksmoothdock#38]
First, thank you, really nice dock.

My distro is openSUSE Leap 42.2 with KDE repo so that I can use the newest version of KDE Plasma.

I'm still investigating but I suspect that there is a resource leak on wallpaper code. When using it, the system usually becomes unstable after some time, even requiring the KDE DE to be killed.

May I help testing the origin of the problem let me know how you want it to done.

Best regards,
André

**Comment by dangvd** [comment]
Thanks Andre.

About the bug, could you tell me more about:
- Your KDE Plasma 5 version?
- How long does it usually take until the problem (freezing) happens?

FYI as KDE Plasma 5 doesn't support different wallpapers on different desktops, I added the feature to KSmoothDock by changing the wallpaper everytime the user changes the desktop. The code to change the wallpaper is simply calling DBus, e.g.:

qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///home/username/Pictures/picture.jpg")}'

(well KSmoothDock calls it using D-Bus API, but it's the same)

Also if it's because of resource leak with KDE Plasma 5 wallpaper setting code, I won't be able to do much about it.

**Comment by andrecbarros** [comment]
Hi,

KDE Frameworks 5.32.0, Apps 17.03.80.

Above 30 changes in a fast cycle of virtual desktops in my machine consistently triggers the freeze. I ran a clean desktop to see if the behavior would still happens and it did. I will do a last test killing also yakuake.

**Comment by andrecbarros** [comment]
OK, disabled all components outside plasma desktop and ksmoothdock.

It took around 200 fast cycles to trigger the issue. It is consistent and there is a high possibility of it be a leak somewhere. Will do the test with just KDE plasma.

**Comment by andrecbarros** [comment]
OK, disabled all components outside plasma desktop and ksmoothdock.

It took around 200 fast cycles to trigger the issue. It is consistent and there is a high possibility of it be a leak somewhere. Will do the test with just KDE plasma.

**Comment by andrecbarros** [comment]
Just cycling without changing the wallpaper does not trigger the issue.

**Comment by andrecbarros** [comment]
OK, updated to latest Plasma (5.94). The issue is gone.

You can close this issue.

Again, thank you, the dock is great.

**Comment by andrecbarros** [comment]
OK, lets see, if I only start ksmoothdock and use the keyboard to cycle through the virtual desktops everything keeps running fine but if I cycle through clicking on ksmoothdock it triggers the issue (freeze).

Perhaps, it may help you nail the problem. If there is anything I can do to help, please, let me know.

Regards,
André

**Comment by dangvd** [comment]
Thanks for the detailed test. I still can't reproduce it yet but I will look more into it.

**Comment by dangvd** [comment]
Hi Andre,

I've made some changes to the code which may or may not help with the issue. If you have some free time, could you pull the latest code from the repo, i.e.
$ git pull https://github.com/dangvd/ksmoothdock master
and run it and see if it improves?

Thanks,
Viet

**Comment by andrecbarros** [comment]
OK, will do it today.
Thanks!
 

    On Thursday, April 20, 2017 1:06 PM, Viet Dang <notifications@github.com> wrote:
 

 Hi Andre,I've made some changes to the code which may or may not help with the issue. If you have some free time, could you pull the latest code from the repo, i.e.
$ git pull https://github.com/dangvd/ksmoothdock master
and run it and see if it improves?Thanks,
Viet—

**Comment by dangvd** [comment]
Thanks! Let me know how it goes.

**Comment by andrecbarros** [comment]
Nice !! No problems so far.

Thank you very much!

**Comment by dangvd** [comment]
Glad to hear that!
