### ISSUE TITLE
Creating a PPA for this package

### ISSUE THREAD

**Issue by Funeoz** [dangvd/ksmoothdock#92]
I would like to create a PPA for your package that will help people to not have the pain for users to build from source especially for new users of Ubuntu and Linux in general. Do you allow me to create it?

**Comment by Funeoz** [comment]
I could also fork your repository and setup Travis CI to build automatically for each commit and push on Launchpad.

**Comment by dangvd** [comment]
Hi,

Thanks for asking and offering to help.

However, I already provide the DEB file to download, so Debian/Ubuntu-based users can already download and install them without building from the source.

Also users usually prefer a more trusted source and the KDE store is a better one than a PPA because it's more well-known and you can see the download count and reviews/comments etc.

Thus personally I'd prefer to continue using the KDE store as the source for DEB distribution.

Regards,
Viet

**Comment by Funeoz** [comment]
Ok, no problem.
